import { Inter, Alumni_Sans, Odibee_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Inter({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
const alumi = Alumni_Sans({
  weight: ["700"],
  family: ["Alumni Sans Pinstripe", "sans-serif"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

const Odibee_Sanss = Odibee_Sans({
  weight: ["400"],
  family: ["Ojuju"],
  sizing: "auto",
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Digital Commerce Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image" href="/vercel.svg" />
      <body className={alumi.className}>{children}</body>
    </html>
  );
}
